### PR TITLE
Add quality checker and set up GitHub Action file to run the checker

### PR DESCRIPTION
**Pull request by philcaz**
Added a quality checker for abbreviation csv files that detects errors due to
- Wrong escape characters
- Wrong starting abbreviation letters (requires further improvement)
- Non-UTF8 characters

and warnings due to
- Duplicate full name / abbreviation entries
- Identical abbreviation as original full name
- Outdated 'Manage.' in abbreviations

Existing issue that cannot be solved:
The check_wrong_beginning_letters() function may consider legitimate abbreviations as 'invalid' because the starting letters of the abbreviation phrases may not obviously refer to the full names, for example

Full: 'Polish Academy of Sciences', Abbrev: 'Acta Phys. Polon. A'
Full: 'Jagellonian University', Abbrev: 'Acta Phys. Polon. B'
Full: 'Universităţii din Timișoara', Abbrev: 'An. Univ. Timișoara Ser. Mat.-Inform.'
Full: 'Universităţii "Ovidius" Constanţa', Abbrev: 'An. Ştiinţ. Univ. Ovidius Constanţa Ser. Mat.'

### CODE REVIEW

**Comment by surluna** [comment]
Hey I've tested the script and inspected the flow on GitHub Action. There are currently more than 200k issues reported, but some of them are actually valid entries. I think the main focus is on the check_wrong_beginning_letters function that fails to recognise some unobvious abbreviation

**Comment by philcaz** [comment]
> Hey I've tested the script and inspected the flow on GitHub Action. There are currently more than 200k issues reported, but some of them are actually valid entries. I think the main focus is on the check_wrong_beginning_letters function that fails to recognise some unobvious abbreviation

Yes I agree. The maintainer advised that the lists contained bugs so it's expected to have substantial errors/warnings in the entries. One entry may also be flagged with multiple warnings/errors, so that adds up to the counts. It's been difficult to implement he check_wrong_beginning_letters function since the lots of the abbreviations could be so random while legitimately referring to their full names. I can try refining the criteria of full/abbrv similarity but it might not reduce the error counts by much.

**Comment by surluna** [comment]
I see. Maybe try getting other check functions to run smoothly then suggest the maintainer to open a new issue specifically for checking the starting letters?

**Comment by philcaz** [comment]
> I see. Maybe try getting other check functions to run smoothly then suggest the maintainer to open a new issue specifically for checking the starting letters?

Sure. I did the best I could with the function

**Comment by surluna** [comment]
Good, ready to merge now.

**Pull request merged**
